### ISSUE TITLE
J8 is very close to mounting hole

### ISSUE THREAD

**Issue by mossmann** [greatfet-hardware/jasmine#8]
It is difficult to install hex screws/standoffs.  Moving J8 (input screw terminal) closer to J3 (USB) would make it a lot easier.

**Comment by yhetti** [comment]
Moved.

**Comment by mossmann** [comment]
resolved in ddbb646
This would have been closed automatically with correct syntax in the commit message.  See: https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords
